### ISSUE TITLE
[review] pre-release checklist

### ISSUE THREAD

**Issue by ShaunSHamilton** [freeCodeCamp/exam-env#16]
These are the main components of the app needing review before `1.0.0`.

- [ ] When a new update is released, it is required to be downloaded before continuing
  - Unless in the middle of an exam attempt
- [ ] Downloading and installing an update is smooth - no app crashing
  - Test logged in and logged out
- [ ] An incompatible device may not get past the splashscreen
- [ ] An incompatible device may not start an exam
- [ ] Only a valid token allows past the login screen
- [ ] During an exam, if a request cannot be made, the screen is paused until connection is re-established
- [ ] If an exam attempt is started, and time still remains, clicking the same exam takes the Camper back to the same attempt
- [ ] If a device camera is disabled during an exam, the exam is paused until the camera is re-enabled
- [ ] If an exam attempt is _too recently_ finished, trying to retake it shows an error explaining why another attempt may not be made
- [ ] If a Camper has not completed the prerequisites for an exam, it should not be possible to attempt to start one

**Comment by a2937** [comment]
What user stories still need worked on, and which ones do you recommend I solve?

**Comment by nieldakarla** [comment]
@ShaunSHamilton I tried running it on my Mac M2 and I can't get passed the instructions screen. After I agree to terms and conditions  I get an error msg saying: "Incompatible. Your device has lost compatibility. restore compatibility, and reload the page to continue with your exam. Camera is unavailable. I give it it access but it won't budge.
